version: "3"

services:
  nodebootstrap-cli-example:
    container_name: nodebootstrap-cli-example
    user: root # avoids ton of volume mounting headaches in dev mode.
    build:
      context: .
    volumes:
      - ./:/opt/app
      # @see: http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html#the-node_modules-volume-trick
      - /opt/app/node_modules
    environment: 
      - NODE_ENV=development
      - NODE_HOT_RELOAD=1
      - NODE_LOGGER_GRANULARLEVELS=1
      - NODE_CONFIG_DISABLE_FILE_WATCH="Y"
    command: node application.js